<script lang="ts">
	import { onMount } from 'svelte';
	import { stateStore, getState, setState, type State } from '$lib/state';

	let state: State = $state(getState());

	onMount(() => {
		state = getState();
        console.log(`shareOption: ${state.shareOption}`);
	});

	function addTag() {
		if (state.userTags.length < 3) {
			state.userTags = [...state.userTags, ''];
			setState(state);
		}
	}

	function removeTag(index: number) {
		state.userTags = state.userTags.filter((_, i) => i !== index);
		setState(state);
	}

	function updateTag(index: number, value: string) {
		state.userTags[index] = value;
		state.userTags = [...state.userTags]; // trigger reactivity
		setState(state);
	}

	// Listen for messages from the extension
	$effect(() => {
		const messageHandler = (event: MessageEvent) => {
			const message = event.data;
			if (message.command === 'tagsGenerated') {
				state.autoTags = message.tags;
				setState(state);
			}
		};

		window.addEventListener('message', messageHandler);
		return () => window.removeEventListener('message', messageHandler);
	});
</script>

<h1 class="flex items-center gap-2 mb-4 font-mono text-center"><img src="https://parakeet.tv/favicon.png" alt="Parakeet.tv" class="w-6 h-6" /> Parakeet.tv</h1>

<!-- Stream Key Section -->
<div class="mb-6">
	<h2 class="text-lg font-semibold mb-2">Stream Key</h2>
	<vscode-textfield
		placeholder="Enter your stream key"
        type="password"
		value={state.streamKey}
		oninput={(e: any) => {
			state.streamKey = e.target.value;
			setState(state);
		}}
		class="w-full p-0"
	></vscode-textfield>
</div>

<!-- Stream Settings Section -->
<div class="mb-6">
	<h2 class="text-lg font-semibold mb-4">Stream Settings</h2>

	<div class="mb-4">
		<label class="block mb-2 font-medium">What to share:</label>
		<vscode-radio-group value={state.shareOption} onchange={(e: any) => {
			state.shareOption = e.target.value;
			setState(state);
		}}>
			<vscode-radio value="current-file">Current file only</vscode-radio>
			<vscode-radio value="directory">Full directory structure</vscode-radio>
			<vscode-radio value="everything">Everything</vscode-radio>
		</vscode-radio-group>
	</div>

	<div class="mb-4">
		<label class="block mb-2 font-medium">Stream title:</label>
		<vscode-textarea
			placeholder="Enter stream title"
			value={state.streamTitle}
			oninput={(e: any) => {
				state.streamTitle = e.target.value;
				setState(state);
			}}
			class="w-full"
		></vscode-textarea>
	</div>

	<div class="mb-4">
		<label class="block mb-2 font-medium">Autogenerated Tags (10 from repo):</label>
		<div class="space-y-2 mb-4">
			{#if state.autoTags.length > 0}
				<div class="flex flex-wrap gap-2">
					{#each state.autoTags as tag}
						<span class="px-3 py-1 bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 rounded-full text-sm border border-gray-300 dark:border-gray-600 cursor-not-allowed select-none" title="Auto-generated tag (readonly)">{tag}</span>
					{/each}
				</div>
			{:else}
				<p class="text-sm text-gray-500 italic">Tags will be generated on extension startup...</p>
			{/if}
		</div>

		<label class="block mb-2 font-medium">Custom Tags (up to 3):</label>
		<div class="space-y-2 mb-2">
			{#each state.userTags as tag, index}
				<div class="flex gap-2 items-center">
					<vscode-textfield
						placeholder="Enter tag"
						value={tag}
						oninput={(e: any) => updateTag(index, e.target.value)}
						class="flex-1"
					></vscode-textfield>
					<vscode-button
						appearance="secondary"
						onclick={() => removeTag(index)}
						class="w-20"
					>
						Remove
					</vscode-button>
				</div>
			{/each}
			{#if state.userTags.length < 3}
				<vscode-button
					appearance="secondary"
					onclick={addTag}
					class="w-24"
				>
					Add Tag
				</vscode-button>
			{/if}
		</div>
	</div>
</div>

<style>
    vscode-textfield {
        padding: 0;
        background-color: transparent !important;
    }
</style>